### ISSUE TITLE
Add tag v1.6

### ISSUE THREAD

**Issue by drejmar** [redhat-cop/pipeline-library#120]
This commit upgrades version from v1.5 to v1.6
Currently there is no v1.6 (only 1.6)

https://github.com/redhat-cop/container-pipelines/commit/5b98095dfa96e284f425cae356b7a8d2de1c616e

**Comment by pabrahamsson** [comment]
Thank you for reporting this, I've updated the release/tag so that we now have [v1.6](https://github.com/redhat-cop/pipeline-library/releases/tag/v1.6)
