### ISSUE TITLE
Need a standard `wait for image signature` method

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/pipeline-library#18]
@sabre1041 https://github.com/redhat-cop/image-scanning-signing-service

**Comment by garethahealy** [comment]
@etsauer ; can you provide more info please.

Would you expect this method to check an image stream until a SHA appears? or something else?

**Comment by pabrahamsson** [comment]
@etsauer can you please elaborate on the requirements for this method?

**Comment by pabrahamsson** [comment]
ping @etsauer

**Comment by etsauer** [comment]
@garethahealy hey, check out this image scanning & signing service. https://github.com/redhat-cop/image-scanning-signing-service

My thought was, yes, to have a method that that looks for a signature to appear on the image that it has built. I'm not sure all of the mechanics of this though. The user has to create several CRDs in order to request the scan and sign, and my thought would be to use a pipeline method to make that a little more self-service. @sabre1041 would be able to provide better information.
