### ISSUE TITLE
Add support for code quality and dependency analysis to builds

### ISSUE THREAD

**Issue by InfoSec812** [redhat-cop/pipeline-library#2]
For Maven builds, support `sonar:sonar` and `dependency-check:check` targets for SonarQube and OWASP Dependency Check

For NPM, add `sonar-scanner` and CLI version of OWASP Dependency Check to build slave and add commands to the Jenkinsfile

**Comment by garethahealy** [comment]
@InfoSec812 ; sonar is supported via:
- https://github.com/redhat-cop/pipeline-library/blob/master/vars/sonarqubeStaticAnalysis.groovy

Is there anything else that can be done in the lib? or can this be closed?

**Comment by pabrahamsson** [comment]
@InfoSec812 please see comment above.

**Comment by InfoSec812** [comment]
@garethahealy I have a concern that this is Maven specific, and SonarQube handles multiple languages and platforms.

**Comment by garethahealy** [comment]
To move to something like the CLI[1], we'd need to include it within a builder image or have the pipeline download it.

[1] https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/

**Comment by InfoSec812** [comment]
I think we can close this as it's somewhat trivial to handle this in Maven, Gradle, and NPM (npx sonar-scanner <args>). We may need to revisit at some later date for GoLang, Python, Ruby, etc...
