### ISSUE TITLE
Need to document a testing strategy for this repo.

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/pipeline-library#20]
As we are starting to get some real contributions to his repo, I'm noticing that the PR review process is fairly slow. Part of this, I think, is because we don't have a good test strategy in place. CI would be great, but I think there's probably a more MVP solution to making reviews run more smoothly.

What I'm picturing is a standard Applier inventory that spins up a jenkins server with this library baked in (we already have the s2i build), plus a test directory for each contribution, containing a jenkinsfile that can be run to exercise the new functionality.

We should document the things that we expect from a contribution, which should include tests

@pabrahamsson @syvanen @sabre1041 @springdo

**Comment by etsauer** [comment]
Here's an example of what I'm talking about. Maybe some of the components here could become common: https://github.com/redhat-cop/pipeline-library/tree/master/test/org/redhatcop/util

**Comment by syvanen** [comment]
Sounds good! It has usually taken me some time to test PRs if there hasn't been a good example pipeline.
But I also noticed that when testing the library, I have to first pull in the change into my own repo as a branch and build against it. Plus right now the Jenkins-s2i is hardcoding to pull in library from your personal repo @etsauer. I'll make a change (PR) for it later today.

**Comment by pabrahamsson** [comment]
A testing strategy is outlined in [TESTING.md](/redhat-cop/pipeline-library/blob/master/TESTING.md).
