### ISSUE TITLE
Need pipeline library user documentation

### ISSUE THREAD

**Issue by Gl4di4torRr** [redhat-cop/pipeline-library#21]
As this starts to become more used, documentation for the user base will be nice. What functions are currently supported, the parameters that users are able to pass to the functions, etc. I am thinking an asciidoc or something like that so each company can expose the documentation internally.

**Comment by Gl4di4torRr** [comment]
@syvanen what are your thoughts on this?

**Comment by syvanen** [comment]
@Gl4di4torRr Now that I got time, I'll write a document that describes the functions and params. Also I'll see if I can extend the functions txt-file that would be displayed inside Jenkins. Problem with these files is that when you include the library from Jenkinsfile, then the UI will never have the help available under "Snippet Generator".

**Comment by garethahealy** [comment]
@syvanen ; did you get round to working on this before leaving RH? i'd am guessing this would be out of date now anyways.

@Gl4di4torRr ; other than the .txt files (i.e.: https://github.com/redhat-cop/pipeline-library/blob/master/vars/clusterCredentials.txt) - what other docs are you thinking about?

**Comment by pabrahamsson** [comment]
Closed due to inactivity, feel free to re-open if needed.
