### ISSUE TITLE
Re-factor applier.groovy to get credentials from Jenkins not OCP

### ISSUE THREAD

**Issue by pcarney8** [redhat-cop/pipeline-library#25]
This block in `applier.groovy`:
```
        openshift.withCluster() {
            def secretData = openshift.selector("secret/${input.secretName}").object().data
            def encodedToken = secretData.token
            env.TOKEN = sh(script:"set +x; echo ${encodedToken} | base64 --decode", returnStdout: true)
        }
```
Assumes that Jenkins is running _on_ openshift. I think that's not a great assumption. 

Change to something like this:
```
node {
  withCredentials([string(credentialsId: 'mytoken', variable: 'TOKEN')]) {
    sh /* WRONG! */ """
      set +x
      curl -H 'Token: $TOKEN' https://some.api/
    """
    sh /* CORRECT */ '''
      set +x
      curl -H 'Token: $TOKEN' https://some.api/
    '''
  }
}
``` 
from: https://jenkins.io/doc/book/pipeline/jenkinsfile/#handling-credentials 

It gets away from that assumption and can still get the secret needed. All you need to know is that you are running _on_ Jenkins. The OCP sync plugin will handle the syncing of an openshift secret to Jenkins (wherever it may live) and then we don't have to worry about knowing that Jenkins is running _on_ Openshift. Jenkins could literally be running wherever and execute this `applier.groovy`

**Comment by garethahealy** [comment]
@pcarney8 ; you can pass in the token via a param:
- https://github.com/redhat-cop/pipeline-library/blob/master/vars/applier.groovy#L42

Can this be closed?

**Comment by pcarney8** [comment]
It doesn't look like that is _exactly_ what I was looking for with this issue. But, the issue is definitely stale and passing in the token will suffice. Closing
