### ISSUE TITLE
Add Slack Integration for Approvals and Deployment Notifications 

### ISSUE THREAD

**Issue by sherl0cks** [redhat-cop/pipeline-library#3]
pending https://github.com/rht-labs/labs-ci-cd/issues/73

**Comment by garethahealy** [comment]
@sherl0cks ; i know you've left RH, but can you provide more info or close please. Not 100% sure what the title is asking for.

**Comment by sherl0cks** [comment]
The idea was to provide something like https://github.com/fabric8io/fabric8-pipeline-library#approve, but without creating a dependency on fabric8.
