### ISSUE TITLE
why is it called registryUrl and not clusterUrl?

### ISSUE THREAD

**Issue by itewk** [redhat-cop/pipeline-library#32]
https://github.com/redhat-cop/pipeline-library/blob/ac47c028be23e859b79113c11170b7525e052364/vars/applier.groovy#L5

this variable is called `registryUrl` which makes it sound like an image registery, but really it is the OCP master API url. Is there a reason for the term confusion?

**Comment by pabrahamsson** [comment]
@itewk I don't think there's a particular reason for the naming. I agree that this could be a bit confusing, would you be ok submitting a PR to change the variable name? If not, I can do so.

**Comment by itewk** [comment]
@pabrahamsson merge request created. https://github.com/redhat-cop/pipeline-library/pull/37
