### ISSUE TITLE
Verify Deployment Error

### ISSUE THREAD

**Issue by haithamshahin333** [redhat-cop/pipeline-library#36]
Seems like this [issue](https://github.com/openshift/jenkins-client-plugin/issues/118) still occurs. If I add some sort of wait/delay it seems to work but otherwise the loop does not get entered and the pipeline stalls in the state pictured below.

The verify deployment function is running immediately after I deploy the application.

![Screen Shot 2019-04-03 at 9 41 42 AM (2)](https://user-images.githubusercontent.com/42976403/55483538-c828a980-55f4-11e9-813a-8c2296f36b37.png)

![Screen Shot 2019-04-03 at 9 45 37 AM (2)](https://user-images.githubusercontent.com/42976403/55483787-56049480-55f5-11e9-8165-24c4c9efbcfe.png)

**Comment by garethahealy** [comment]
@haithamshahin333 ; can you provide more info please. if you can create a git repo showing the issue (i.e.: a simple unit test), that would be great.

**Comment by pabrahamsson** [comment]
@haithamshahin333 are you able to provide more details or can this issue be closed?

**Comment by garethahealy** [comment]
since no more info has been provided in the past month, can we close?

CC @redhat-cop/day-in-the-life

**Comment by pabrahamsson** [comment]
@haithamshahin333 I'm closing this issue, feel free to re-open with additional information.
