### ISSUE TITLE
verify deployment skip ssl

### ISSUE THREAD

**Issue by Gl4di4torRr** [redhat-cop/pipeline-library#39]
We have been having issues on one of our clusters where the certificate has expired (yes, we need to update the cert). However, from the app teams perspective, this makes their pipeline fail on `verifyDeployment`. The upgrade of the certificate is not very high on our priority because releasing a later version of OpenShift is greater than improving this cluster.

**Comment by garethahealy** [comment]
@Gl4di4torRr ; you can pass in the cluster id via:
- https://github.com/redhat-cop/pipeline-library/blob/master/vars/verifyDeployment.groovy#L16

Which can be resolved from central config that allows you to skip tls:
- https://github.com/openshift/jenkins-client-plugin#centralizing-cluster-configuration

Is that a workable solution? if so, can this be closed?

**Comment by pabrahamsson** [comment]
Solution/workaround provided by @garethahealy
