### ISSUE TITLE
Add Blue / Green Support At the Routing Tier

### ISSUE THREAD

**Issue by sherl0cks** [redhat-cop/pipeline-library#4]

**Comment by Gl4di4torRr** [comment]
@sherl0cks what were your thoughts to approaching this problem?

**Comment by sherl0cks** [comment]
well its been awhile, but I think what is documented here is in line. not sure if it really needs a library or not https://docs.openshift.com/container-platform/3.11/dev_guide/deployments/advanced_deployment_strategies.html

**Comment by Gl4di4torRr** [comment]
@sherl0cks yeah, i am not sure how this really becomes a library

**Comment by Gl4di4torRr** [comment]
@sherl0cks maybe we should close the blue/green issues?
