### ISSUE TITLE
Add an example for a Maven Multi-Module Pipeline

### ISSUE THREAD

**Issue by InfoSec812** [redhat-cop/pipeline-library#9]
I have a Maven Multi-Module project (https://github.com/rhoar-shootout/rhoar-vertx) and I am wondering how to wire up a multimodule Maven project into Jenkins for building several containers for OpenShift. In my example, there are 4 different images which should be built and deployed. Should it be done with a single Jenkinsfile at the top level? One for each service? I will be experimenting with different options and report back here if I do not get other feedback.

**Comment by gdubya** [comment]
Any progress on this, @InfoSec812 ? I'm wondering the same thing now :)

**Comment by InfoSec812** [comment]
The consensus from out team was that each module should have it's own Jenkinsfile and it's own Pipeline.

**Comment by pabrahamsson** [comment]
@InfoSec812 is there anything you'd like to add to this issue around the team's conclusion before we close out this issue?

**Comment by InfoSec812** [comment]
One thing I would add is that if you are going to create a multi-module project, you should create the individual modules are `git submodule`s. This allows you to create webhooks for the individual subprojects, and that makes this whole thing work better.
